version: '3.8'
services:
  library-app-borrow:
    image: damou/library-app-borrow:6d62519d9e1afd8f37807997064dedc27ef9e953
    container_name: library-app-borrow-container
    ports:
      - "8081:8083"
    networks:
      - library-app-network
    env_file:
      - .env

networks:
  library-app-network:
    external: true